# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

###############################################################################
###############################################################################
##   vagrant box add generic/ubuntu1604    ##                                ##
##                                                                           ##
##    	==> box: Loading metadata for box 'generic/ubuntu1604'               ##
##    		box: URL: https://vagrantcloud.com/generic/ubuntu1604            ##
##    	This box can work with multiple providers! The providers that it     ##
##    	can work with are listed below. Please review the list and choose    ##
##    	the provider you will be working with.                               ##
##    	                                                                     ##
##    	1) hyperv                                                            ##
##    	2) libvirt                                                           ##
##    	3) parallels                                                         ##
##    	4) virtualbox                                                        ##
##    	5) vmware_desktop                                                    ##
##    	                                                                     ##
##    	Enter your choice: 1                                                 ##
##                                                                           ##
##   vagrant init generic/ubuntu1604                                         ##
##   vagrant up --provider=hyperv                                            ##
##   vagrant status                                                          ##
##   vagrant ssh                                                             ##
##   vagrant halt                                                            ##
##   vagrant destroy                                                         ##
###############################################################################
###############################################################################

# Vagrant Variables

vagrant_box = "generic/ubuntu1604"
vagrant_network = "public_network"
vagrant_hyperv_switch_type = 'Default Switch' # "External Switch" or "Internal Switch" or "Default Switch"
vagrant_terraform_install_script = "terraform_gcp.sh"
vagrant_vm_provider = "hyperv"


Vagrant.configure(2) do |config|

  config.vm.define "terraform" do |terraform|

    terraform.vm.hostname = "terraform"
    terraform.vm.box = vagrant_box
    terraform.vm.network vagrant_network, bridge: vagrant_hyperv_switch_type
    terraform.vm.provision :shell, path: vagrant_terraform_install_script

    terraform.vm.provider vagrant_vm_provider do |vb|
	
      vb.memory = "1024"

    end

  end
  
end

	
