# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

###############################################################################
###############################################################################
##   vagrant box add generic/ubuntu1604    ##                                ##
##                                                                           ##
##    	==> box: Loading metadata for box 'generic/ubuntu1604'               ##
##    		box: URL: https://vagrantcloud.com/generic/ubuntu1604            ##
##    	This box can work with multiple providers! The providers that it     ##
##    	can work with are listed below. Please review the list and choose    ##
##    	the provider you will be working with.                               ##
##    	                                                                     ##
##    	1) hyperv                                                            ##
##    	2) libvirt                                                           ##
##    	3) parallels                                                         ##
##    	4) virtualbox                                                        ##
##    	5) vmware_desktop                                                    ##
##    	                                                                     ##
##    	Enter your choice: 1                                                 ##
##                                                                           ##
##   vagrant init generic/ubuntu1604                                         ##
##   vagrant up --provider=hyperv                                            ##
##   vagrant status                                                          ##
##   vagrant ssh                                                             ##
##   vagrant halt                                                            ##
##   vagrant destroy                                                         ##
###############################################################################
###############################################################################

###############################################################################################################################################
###############################################################################################################################################
##                                                                                                                                           ##
##  PS D:\Docker\Practice\Services> docker swarm init                                                                                        ##
##  Swarm initialized: current node (ku78i5y4qc083ddi0n4wxc7xb) is now a manager.                                                            ##
##                                                                                                                                           ##
##  To add a worker to this swarm, run the following command:                                                                                ##
##                                                                                                                                           ##
##      docker swarm join --token SWMTKN-1-2vwxsc6ymh6rcnltg3jhtgud3ka32nf48jmu4raygpnwa0j13q-c09u3dy4n95c0bjic5zpy2ldp 192.168.65.3:2377	 ##
##                                                                                                                                           ##
##  To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.                                       ##
##                                                                                                                                           ##
##  docker swarm leave --force                                                                                                               ##
##                                                                                                                                           ##
###############################################################################################################################################
###############################################################################################################################################

# Vagrant Variables

vagrant_box = "generic/ubuntu1604"
vagrant_network = "public_network"
#vagrant_hyperv_switch_type = 'dhcp'
vagrant_hyperv_switch_type = 'Default Switch'
# "External Switch" or "Internal Switch" or "Default Switch"
vagrant_install_script = "kubernetes.sh"
vagrant_vm_provider = "hyperv"


Vagrant.configure(2) do |config|

  config.vm.define "k8s_master" do |k8s_master|

    k8s_master.vm.hostname = "k8s-master"
    k8s_master.vm.box = vagrant_box
    k8s_master.vm.network vagrant_network, bridge: vagrant_hyperv_switch_type
    #k8s_master.vm.provision :shell, path: vagrant_install_script

    k8s_master.vm.provider vagrant_vm_provider do |vb|

      vb.memory = "1024"

    end

  end
  
  config.vm.define "k8s_node_1" do |k8s_node_1|

    k8s_node_1.vm.hostname = "k8s-node-1"
    k8s_node_1.vm.box = vagrant_box
    k8s_node_1.vm.network vagrant_network, bridge: vagrant_hyperv_switch_type
    #k8s_node_1.vm.provision :shell, path: vagrant_install_script

    k8s_node_1.vm.provider vagrant_vm_provider do |vb|

      vb.memory = "1024"

    end

  end

  config.vm.define "k8s_node_2" do |k8s_node_2|

    k8s_node_2.vm.hostname = "k8s-node-2"
    k8s_node_2.vm.box = vagrant_box
    k8s_node_2.vm.network vagrant_network, bridge: vagrant_hyperv_switch_type
    #k8s_node_2.vm.provision :shell, path: vagrant_install_script

    k8s_node_2.vm.provider vagrant_vm_provider do |vb|

      vb.memory = "1024"

    end

  end

  config.vm.define "k8s_node_3" do |k8s_node_3|

    k8s_node_3.vm.hostname = "k8s-node-3"
    k8s_node_3.vm.box = vagrant_box
    k8s_node_3.vm.network vagrant_network, bridge: vagrant_hyperv_switch_type
    #k8s_node_3.vm.provision :shell, path: vagrant_install_script

    k8s_node_3.vm.provider vagrant_vm_provider do |vb|

      vb.memory = "1024"

    end

  end  
  
end

	
