# Hyper V based Vagrantfile

###############################################################################
###############################################################################
##   vagrant box add generic/ubuntu1604    ##                                ##
##                                                                           ##
##    	==> box: Loading metadata for box 'generic/ubuntu1604'               ##
##    		box: URL: https://vagrantcloud.com/generic/ubuntu1604            ##
##    	This box can work with multiple providers! The providers that it     ##
##    	can work with are listed below. Please review the list and choose    ##
##    	the provider you will be working with.                               ##
##    	                                                                     ##
##    	1) hyperv                                                            ##
##    	2) libvirt                                                           ##
##    	3) parallels                                                         ##
##    	4) virtualbox                                                        ##
##    	5) vmware_desktop                                                    ##
##    	                                                                     ##
##    	Enter your choice: 1                                                 ##
##                                                                           ##
##   vagrant init generic/ubuntu1604                                         ##
##   vagrant up --provider=hyperv                                            ##
##   vagrant status                                                          ##
##   vagrant ssh                                                             ##
##   vagrant halt                                                            ##
##   vagrant destroy                                                         ##
###############################################################################
###############################################################################

# Vagrant Variables

vagrant_box = "generic/ubuntu1604"
vagrant_network = "public_network"
#vagrant_hyperv_switch_type = 'dhcp'
vagrant_hyperv_switch_type = 'Default Switch'
# "External Switch" or "Internal Switch" or "Default Switch"
#vagrant_install_script = "docker.sh"
vagrant_spinnaker_install_script = "spinnaker.sh"
vagrant_vm_provider = "hyperv"
vagrant_spinnaker_guest_port = "8084"
vagrant_spinnaker_host_port = "9084"
vagrant_guest_synced_folder = "D:/Vagrant/Spinnaker/.hal"
vagrant_host_folder_to_sync = "/home/spinnaker/.hal"


Vagrant.configure(2) do |config|

  config.vm.define "spinnaker" do |spinnaker|

    spinnaker.vm.hostname = "spinnaker"
    spinnaker.vm.box = vagrant_box
    spinnaker.vm.network vagrant_network, bridge: vagrant_hyperv_switch_type
    spinnaker.vm.provision :shell, path: vagrant_spinnaker_install_script
	spinnaker.vm.network "forwarded_port", guest: vagrant_spinnaker_guest_port, host: vagrant_spinnaker_host_port
	spinnaker.vm.synced_folder vagrant_guest_synced_folder, vagrant_host_folder_to_sync

    spinnaker.vm.provider vagrant_vm_provider do |vb|
	
      vb.memory = "1024"

    end

  end
  
end

	
